import pandas as pd

# List of 100 corrected and formatted objects
data = [
    {"type": "CasualDining, FineDining"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "CasualDining"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FineDining"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, CoffeeCafes, Catering"},
    {"type": "CoffeeCafes"},
    {"type": "CoffeeCafes, CasualDining, FineDining, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, Catering"},
    {"type": "FastFoodChains, CasualDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FineDining, CasualDining"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining"},
    {"type": "CasualDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, Catering"},
    {"type": "CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining, FineDining"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "CasualDining, FineDining"},
    {"type": "CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, Catering"},
    {"type": "CoffeeCafes"},
    {"type": "FastFoodChains"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FineDining, CasualDining"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, Catering"},
    {"type": "CoffeeCafes, FineDining"},
    {"type": "CoffeeCafes, CasualDining, Catering"},
    {"type": "FineDining, CasualDining, CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CoffeeCafes"},
    {"type": "CoffeeCafes, CasualDining"},
    {"type": "CasualDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FineDining, CasualDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "FastFoodChains, CoffeeCafes, CasualDining"},
    {"type": "CoffeeCafes, CasualDining, Catering"},
    {"type": "FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, CoffeeCafes"},
    {"type": "CasualDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, CoffeeCafes, Catering"},
    {"type": "CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "Business Services"},
    {"type": "Business"},
    {"type": "Support Services"},
    {"type": "Food Services"},
    {"type": "FastFoodChains"},
    {"type": "Casual Dining"},
    {"type": "Fine Dining"},
    {"type": "Coffee Cafes"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FineDining, CasualDining"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining"},
    {"type": "CasualDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, Catering"},
    {"type": "CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining, FineDining"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "CasualDining, FineDining"},
    {"type": "CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, Catering"},
    {"type": "CoffeeCafes"},
    {"type": "FastFoodChains"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FineDining, CasualDining"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, Catering"},
    {"type": "CoffeeCafes, FineDining"},
    {"type": "CoffeeCafes, CasualDining, Catering"},
    {"type": "FineDining, CasualDining, CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CoffeeCafes"},
    {"type": "CoffeeCafes, CasualDining"},
    {"type": "CasualDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FineDining, CasualDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "FastFoodChains, CoffeeCafes, CasualDining"},
    {"type": "CoffeeCafes, CasualDining, Catering"},
    {"type": "FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining"},
    {"type": "FastFoodChains, CasualDining, CoffeeCafes, FineDining"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "CasualDining"},
    {"type": "CasualDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining"},
    {"Type": "Casual Dining", "options": "Fast Food Chains, Coffee Cafes, Fine Dining"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "CasualDining, FineDining, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining, FineDining, Catering, CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining"},
    {"type": "FastFoodChains, CasualDining, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining"},
    {"type": "CasualDining"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, Catering"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining"},
    {"type": "CasualDining"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining"},
    {"type": "CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining"},
    {"type": "CasualDining"},
    {"type": "FastFoodChains, CasualDining, CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CoffeeCafes"},
    {"type": "CoffeeCafes"},
    {"type": "FastFoodChains, CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, FineDining"},
    {"type": "CasualDining, CoffeeCafes, Catering"},
    {"type": "CoffeeCafes"},
    {"type": "CoffeeCafes"},
    {"type": "FastFoodChains, CoffeeCafes"},
    {"type": "CasualDining"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FastFoodChains"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes"},
    {"type": "FastFoodChains"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Cater"},
    {"type": "Catering"},
    {"type": "Quick Service, Fast Casual, Coffee, Casual Dining, Fine Dining, Catering"},
    {"type": "FastFoodChains, CasualDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "QuickService, FastCasual, CasualDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "Quick-Service, Fast-Casual, Casual Dining"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains"},
    {"type": "Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CoffeeCafes"},
    {"type": "FastFoodChains,CasualDining,Catering"},
    {"type": "CasualDining, FastFoodChains, Catering"},
    {"type": "Casual Dining, Coffee Cafes, Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, Catering, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains"},
    {"type": "CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, CoffeeCafes, Catering"},
    {"type": "FineDining,CasualDining,CoffeeCafes,Catering"},
    {"type": "CasualDining, FineDining, CoffeeCafes"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, Catering"},
    {"type": "CasualDining, FineDining, Catering"},
    {"type": "CasualDining, FineDining, Catering"},
    {"type": "FastFoodChains"},
    {"type": "CoffeeCafes"},
    {"type": "Fast Food Chains, Casual Dining, Fine Dining, Coffee Cafes, Catering"},
    {"type": "CasualDining, FineDining, BeachClub"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, Catering"},
    {"type": "CasualDining, FineDining, Catering"},
    {"type": "CasualDining, FineDining, Catering"},
    {"type": "FastFoodChains"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "Global Financial Service"},
    {"type": "NonAlcoholic CoffeeCafes"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "CasualDining, FineDining"},
    {"type": "CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "NonAlcoholic CoffeeCafes"},
    {"type": "CasualDining"},
    {"type": "CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "CasualDining,FineDining"},
    {"type": "FastFoodChains, CasualDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "Fast Food Chains, Casual Dining, Fine Dining, Coffee Cafes, Catering"},
    {"type": "FastFoodChains,CasualDining,FineDining,CoffeeCafes,Catering"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining"},
    {"type": "FastFoodChains, CasualDining, FineDining, CoffeeCafes, Catering"},
    {"type": "No"},

]


# Create a DataFrame with a column named "restaurant_types"
df = pd.DataFrame(data, columns=["restaurant_types"])

# Display the DataFrame
print(df)
